# Generated by Django 4.2.3 on 2023-09-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotn_game', '0004_remove_room_creator_remove_room_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
